DROP DATABASE tractomaq;
CREATE DATABASE tractomaq;
\c tractomaq
SET datestyle TO "ISO,YMD";

CREATE TABLE IF NOT EXISTS usuario (
  id_usuario INT GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(60) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  tipo SMALLINT NOT NULL,
  CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
  CONSTRAINT uk_usuario_nome UNIQUE (nome)
);
COMMENT ON COLUMN usuario.tipo IS '0-Administrador; 1-Regular';

CREATE TABLE IF NOT EXISTS pessoa (
  id_pessoa INT GENERATED BY DEFAULT AS IDENTITY,
  tipo SMALLINT NOT NULL,
  nome VARCHAR(60) NOT NULL,
  endereco VARCHAR(100) NOT NULL,
  telefone VARCHAR(13) NOT NULL, 
  email VARCHAR(60) NOT NULL,
  cpf VARCHAR(11),
  cnpj VARCHAR(14),
  razao_social VARCHAR(60),
  CONSTRAINT pk_pessoa PRIMARY KEY (id_pessoa),
  CONSTRAINT uk_pessoa_cpf UNIQUE (cpf),
  CONSTRAINT uk_pessoa_cnpj UNIQUE (cnpj)
);
COMMENT ON COLUMN pessoa.tipo IS '0-Fisica; 1-Juridica';

CREATE TABLE IF NOT EXISTS produtos (
  id_produto INT GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(60) NOT NULL,
  quantidade INT NOT NULL,
  valor_uni NUMERIC(12,2) NOT NULL,
  descricao TEXT,
  categoria VARCHAR(60),
  marca VARCHAR(60),
  CONSTRAINT pk_produtos PRIMARY KEY (id_produto)
);

CREATE TABLE IF NOT EXISTS maquina (
  id_maquina INT GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(60) NOT NULL,
  descricao TEXT,
  CONSTRAINT pk_maquina PRIMARY KEY (id_maquina)
);

CREATE TABLE IF NOT EXISTS compra (
  id_compra INT GENERATED BY DEFAULT AS IDENTITY,
  loc_entrega VARCHAR(100) NOT NULL,
  valor NUMERIC(12,2) NOT NULL,
  dt_emissao DATE NOT NULL,
  dt_vencimento DATE NOT NULL,
  dt_entrega DATE,
  dt_pagamento DATE,
  id_pessoa INT NOT NULL,
  CONSTRAINT pk_compra PRIMARY KEY (id_compra),
  CONSTRAINT fk_compra_pessoa FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa)
);

CREATE TABLE IF NOT EXISTS ordemservico (
  id_ordem_servico INT GENERATED BY DEFAULT AS IDENTITY,
  dt_servico DATE NOT NULL,
  loc_servico VARCHAR(100) NOT NULL,
  descricao TEXT,
  id_pessoa INT NOT NULL,
  CONSTRAINT pk_ordemservico PRIMARY KEY (id_ordem_servico),
  CONSTRAINT fk_ordemservico_pessoa FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa)
);

CREATE TABLE IF NOT EXISTS servico (
  id_servico INT GENERATED BY DEFAULT AS IDENTITY,
  id_ordem_servico INT NOT NULL,
  valor NUMERIC(12,2) NOT NULL,
  dt_emissao DATE NOT NULL,
  dt_vencimento DATE NOT NULL,
  quilometros NUMERIC(6,2) NOT NULL,
  horas NUMERIC(5,2) NOT NULL,
  dt_pagamento DATE,
  descricao TEXT,
  CONSTRAINT pk_servico PRIMARY KEY (id_servico),
  CONSTRAINT fk_servico_ordemservico FOREIGN KEY (id_ordem_servico) REFERENCES ordemservico(id_ordem_servico),
  CONSTRAINT uk_servico_ordemservico UNIQUE (id_ordem_servico)
);

CREATE TABLE IF NOT EXISTS compatibilidade (
  id_compatibilidade INT GENERATED BY DEFAULT AS IDENTITY,
  id_produto INT NOT NULL,
  id_maquina INT NOT NULL,
  CONSTRAINT pk_compatibilidade PRIMARY KEY (id_compatibilidade),
  CONSTRAINT fk_compatibilidade_produtos FOREIGN KEY (id_produto) REFERENCES produtos(id_produto),
  CONSTRAINT fk_compatibilidade_maquina FOREIGN KEY (id_maquina) REFERENCES maquina(id_maquina)
);

CREATE TABLE IF NOT EXISTS consumocompra (
  id_consumocompra INT GENERATED BY DEFAULT AS IDENTITY,
  quantidade INT NOT NULL,
  id_produto INT NOT NULL,
  id_compra INT NOT NULL,
  CONSTRAINT pk_consumocompra PRIMARY KEY (id_consumocompra),
  CONSTRAINT fk_consumocompra_produtos FOREIGN KEY (id_produto) REFERENCES produtos(id_produto),
  CONSTRAINT fk_consumocompra_compra FOREIGN KEY (id_compra) REFERENCES compra(id_compra)
);

CREATE TABLE IF NOT EXISTS consumoservico (
  id_consumoservico INT GENERATED BY DEFAULT AS IDENTITY,
  quantidade INT NOT NULL,
  id_produto INT NOT NULL,
  id_servico INT NOT NULL,
  CONSTRAINT pk_consumoservico PRIMARY KEY (id_consumoservico),
  CONSTRAINT fk_consumoservico_produtos FOREIGN KEY (id_produto) REFERENCES produtos(id_produto),
  CONSTRAINT fk_consumoservico_servico FOREIGN KEY (id_servico) REFERENCES servico(id_servico)
);
